# Generated by Django 5.2.15 on 2026-07-21 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('admin_id', models.CharField(db_column='Admin_ID', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('email', models.EmailField(db_column='Email', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('role', models.CharField(db_column='Role', max_length=10)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
            ],
            options={
                'db_table': 'Admin_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(db_column='Brand_ID', max_length=15, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_column='Brand_name', max_length=20)),
            ],
            options={
                'db_table': 'Brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(db_column='Cart_ID', max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(db_column='Cat_ID', max_length=15, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(db_column='Cat_Name', max_length=20)),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.CharField(db_column='Color_ID', max_length=15, primary_key=True, serialize=False)),
                ('color_name', models.CharField(db_column='Color_Name', max_length=15)),
            ],
            options={
                'db_table': 'Color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(db_column='Order_ID', max_length=15, primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(db_column='OrderDate')),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(db_column='Order_Status', max_length=10)),
            ],
            options={
                'db_table': 'Orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerid', models.CharField(db_column='SellerID', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('shopname', models.CharField(blank=True, db_column='ShopName', max_length=50, null=True)),
                ('shopno', models.CharField(blank=True, db_column='ShopNo', max_length=10, null=True)),
                ('phone', models.BigIntegerField(db_column='Phone', unique=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=50, null=True)),
                ('pswrd', models.CharField(db_column='Pswrd', max_length=128)),
            ],
            options={
                'db_table': 'Seller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.CharField(db_column='Size_ID', max_length=15, primary_key=True, serialize=False)),
                ('size_no', models.IntegerField(db_column='Size_no')),
            ],
            options={
                'db_table': 'Size',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.CharField(db_column='UserId', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('phone', models.BigIntegerField(db_column='Phone', unique=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(db_column='Payment_ID', max_length=15, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(db_column='Payment_Method', max_length=10)),
                ('payment_status', models.CharField(db_column='Payment_Status', max_length=10)),
                ('payment_date', models.DateTimeField(db_column='Payment_Date')),
                ('order_id', models.ForeignKey(db_column='Order_ID', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.order')),
            ],
            options={
                'db_table': 'Payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.CharField(db_column='Prod_ID', max_length=15, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(db_column='Prod_Name', max_length=30)),
                ('dscrptn', models.CharField(blank=True, db_column='Dscrptn', max_length=50, null=True)),
                ('brand_id', models.ForeignKey(db_column='Brand_ID', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.brand')),
                ('cat_id', models.ForeignKey(db_column='Cat_ID', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
                ('sellerid', models.ForeignKey(db_column='SellerID', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.seller')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(db_column='Image_ID', max_length=15, primary_key=True, serialize=False)),
                ('img_url', models.CharField(blank=True, db_column='Img_url', max_length=100, null=True)),
                ('alt_text', models.CharField(blank=True, db_column='alt_text', max_length=50, null=True)),
                ('prod_id', models.ForeignKey(db_column='Prod_ID', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
            options={
                'db_table': 'Image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.CharField(db_column='Variant_ID', max_length=15, primary_key=True, serialize=False)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('stockquantity', models.IntegerField(db_column='StockQuantity')),
                ('sku', models.CharField(db_column='SKU', max_length=50, unique=True)),
                ('color_id', models.ForeignKey(db_column='Color_ID', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.color')),
                ('image_id', models.ForeignKey(blank=True, db_column='Image_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='api.image')),
                ('prod_id', models.ForeignKey(db_column='Prod_ID', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product')),
                ('size_id', models.ForeignKey(db_column='Size_ID', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.size')),
            ],
            options={
                'db_table': 'Product_Variant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderitem_id', models.CharField(db_column='OrderItem_ID', max_length=15, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('priceatpurchase', models.DecimalField(db_column='PriceAtPurchase', decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(db_column='Order_ID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('variant_id', models.ForeignKey(db_column='Variant_ID', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.productvariant')),
            ],
            options={
                'db_table': 'Order_Item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartitem_id', models.CharField(db_column='CartItem_ID', max_length=15, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('cart_id', models.ForeignKey(db_column='Cart_ID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cart')),
                ('variant_id', models.ForeignKey(db_column='Variant_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.productvariant')),
            ],
            options={
                'db_table': 'Cart_Item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('saddrid', models.CharField(db_column='SAddrID', max_length=15, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('pincode', models.IntegerField(blank=True, db_column='PinCode', null=True)),
                ('sellerid', models.ForeignKey(db_column='SellerID', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.seller')),
            ],
            options={
                'db_table': 'SellerAddress',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.users'),
        ),
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='api.users'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addrid', models.CharField(db_column='AddrID', max_length=15, primary_key=True, serialize=False)),
                ('home_no', models.CharField(blank=True, db_column='Home_no', max_length=10, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=30, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('pincode', models.IntegerField(blank=True, db_column='PinCode', null=True)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.users')),
            ],
            options={
                'db_table': 'Address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.CharField(db_column='Wishlist_ID', max_length=15, primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(db_column='Added_Date')),
                ('prod_id', models.ForeignKey(db_column='Prod_ID', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='api.product')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='api.users')),
            ],
            options={
                'db_table': 'Wishlist',
                'managed': True,
            },
        ),
    ]
