# Generated by Django 5.2.15 on 2026-08-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.CharField(blank=True, db_column='Img_url', max_length=2048, null=True),
        ),
    ]
