# Generated by Django 5.2.15 on 2026-09-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dscrptn',
            field=models.TextField(blank=True, db_column='Dscrptn', null=True),
        ),
    ]
